/*
 * DISTRHO Plugin Framework (DPF)
 * Copyright (C) 2012-2024 Filipe Coelho <falktx@falktx.com>
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
 * REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
 * INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
 * LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
 * OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 * PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_PLUGIN_INFO_H_INCLUDED

// #define DISTRHO_PLUGIN_BRAND "Nanashi."
#define DISTRHO_PLUGIN_BRAND "Voicevox"
#ifdef DEBUG
#define DISTRHO_PLUGIN_NAME "VVVST (Debug)"
#else
#define DISTRHO_PLUGIN_NAME "VVVST"
#endif
#define DISTRHO_PLUGIN_URI                                                     \
  "https://github.com/sevenc-nanashi/vvvst-dpf-rust"

// #define DISTRHO_PLUGIN_BRAND_ID Vcvx
#define DISTRHO_PLUGIN_BRAND_ID ScNs
#define DISTRHO_PLUGIN_UNIQUE_ID V3st

// #define DISTRHO_PLUGIN_CLAP_ID "jp.hiroshiba.vvvst"
#define DISTRHO_PLUGIN_CLAP_ID "com.sevenc-nanashi.vvvst-dpf-rust"


#define DISTRHO_PLUGIN_HAS_UI 1
#define DISTRHO_PLUGIN_HAS_EMBED_UI 1
#define DISTRHO_PLUGIN_HAS_EXTERNAL_UI 1
#define DISTRHO_PLUGIN_IS_RT_SAFE 1
#define DISTRHO_PLUGIN_NUM_INPUTS 0
#define DISTRHO_PLUGIN_NUM_OUTPUTS 2
#define DISTRHO_PLUGIN_WANT_STATE 1
#define DISTRHO_PLUGIN_WANT_FULL_STATE 1
#define DISTRHO_PLUGIN_WANT_DIRECT_ACCESS 1
#define DISTRHO_PLUGIN_WANT_TIMEPOS 1

#define DISTRHO_UI_USER_RESIZABLE 1

#define DISTRHO_PLUGIN_VST3_CATEGORIES "Instrument"

#define DISTRHO_UI_DEFAULT_WIDTH 1080
#define DISTRHO_UI_DEFAULT_HEIGHT 720

#endif // DISTRHO_PLUGIN_INFO_H_INCLUDED
